routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {
    return view('landing');
});


Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/login', function () {
        return view('welcome');
    });
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::get('/engineers', 'admin\UsersController@listEngineers');
    Route::resource('/orders', 'admin\OrderController');
    Route::resource('/problems', 'admin\ProblemController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/states', 'admin\StatesController');
    Route::resource('/phone_types', 'admin\PhoneTypesController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/products', 'admin\ProductController');
    Route::get('/phone_models/samsung', 'admin\PhoneModelsController@listSamsung');
    Route::get('/phone_models/huawei', 'admin\PhoneModelsController@listHuawei');
    Route::resource('/phone_models', 'admin\PhoneModelsController');
    Route::get('/phone_colors/samsung', 'admin\PhoneColorsController@listSamsung');
    Route::get('/phone_colors/huawei', 'admin\PhoneColorsController@listHuawei');
    Route::resource('/phone_colors', 'admin\PhoneColorsController');
    Route::resource('/accessory_types', 'admin\AccessoriesTypesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/transactions', 'admin\TransactionsController');
    Route::get('/transactions/{id}/paid', 'admin\TransactionsController@paid');
    Route::get('/transactions/{id}/ban', 'admin\TransactionsController@ban');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');

    Route::get('/notifications', 'admin\UsersController@showNotification');
    Route::post('/send_notification', 'admin\UsersController@sendNotification');


});
Route::get('/getStates', function () {
    $city_id = Input::get('city_id');
    $states = \App\Models\State::where('city_id', '=', $city_id)->get();
    return json_encode($states);
});

app/Http/Controllers/admin/PhoneTypesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\PhoneTypes;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PhoneTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $phoneTypes=PhoneTypes::orderBy('created_at','ASC')->paginate(10);
        return view('admin.phoneTypes.index',compact('phoneTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.phoneTypes.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
        ]);
       $phoneType= PhoneTypes::create($request->except('icon'));

        if ($request->hasFile('icon')) {
            $request->validate([

                'icon' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = str_random(10) . '.' . $request->file('icon')->extension();
            $request->file('icon')->move(
                base_path() . '/public/uploads/phoneTypes/', $imageName
            );
            $phoneType->icon = '/uploads/phoneTypes/' . $imageName;
            $phoneType->save();

        }
        return redirect('/webadmin/phone_types')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم اضافة نوع الهاتف بنجاح']));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $phoneType=PhoneTypes::find($id);
        return view('admin.phoneTypes.edit',compact('phoneType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
        ]);
        $phoneType=PhoneTypes::find($id);
        $phoneType->update($request->except('icon'));

        if ($request->hasFile('icon')) {
            $request->validate([

                'icon' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = str_random(10) . '.' . $request->file('icon')->extension();
            $request->file('icon')->move(
                base_path() . '/public/uploads/phoneTypes/', $imageName
            );
            $phoneType->icon = '/uploads/phoneTypes/' . $imageName;
            $phoneType->save();

        }
        return redirect('/webadmin/phone_types')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم تعديل نوع الهاتف بنجاح']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PhoneTypes::destroy($id);
        return redirect('/webadmin/phone_types')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم حذف نوع الهاتف بنجاح']));

    }
}

resources/views/admin/phoneTypes/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة نوع هاتف
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/phone_types')}}" class="m-menu__link">
            <span class="m-menu__link-text"> أنواع الهواتف</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة نوع هاتف</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة نوع هاتف
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/phone_types" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.phoneTypes.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/phoneTypes/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل نوع هاتف
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/phone_types')}}" class="m-menu__link">
            <span class="m-menu__link-text">أنواع الهواتف </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل نوع هاتف </span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل نوع هاتف
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($phoneType,['route' => ['phone_types.update' , $phoneType->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">
            @include('admin.phoneTypes.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/phoneTypes/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">نوع الهاتف بالعربية : </label>
    <div class="col-lg-4{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
        {!! Form::text('name_ar',null,['class'=>'form-control m-input','autofocus','placeholder'=>"نوع الهاتف بالعربية"]) !!}
        @if ($errors->has('name_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_ar') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-2 col-form-label">نوع الهاتف بالانجليزية : </label>
    <div class="col-lg-5{{ $errors->has('name_en') ? ' has-danger' : '' }}">
        {!! Form::text('name_en',null,['class'=>'form-control m-input','placeholder'=>"نوع الهاتف بالانجليزية"]) !!}
        @if ($errors->has('name_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_en') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الايقونة: </label>
    <div class="col-lg-10{{ $errors->has('icon') ? ' has-danger' : '' }}">

        <input type="file" name="icon"   class="form-control uploadinput">
        @if ($errors->has('icon'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('icon') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($phoneType) && $phoneType->icon)
    <div class="row">




        <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

            <img
                    data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                    alt="First slide [800x4a00]"
                    src="{{$phoneType->icon}}"
                    style="height: 150px; width: 150px"
                    data-holder-rendered="true">
        </div>

    </div>
@endif

resources/views/admin/phoneTypes/index.blade.php
@extends('admin.layouts.app')
@section('title')
    أنواع الهواتف
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">أنواع الهواتف</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        أنواع الهواتف
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('phone_types.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضف نوع هاتف</a></div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_country">
                <thead>
                <tr>
                    <th>#</th>
                    <th>نوع الهاتف بالعربية</th>
                    <th> نوع الهاتف بالانجليزية</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($phoneTypes as $index=>$phoneType)
                    <tr>
                        <td>{{$index + $phoneTypes->firstItem()}}</td>
                        <td>{{$phoneType->name_ar}}</td>
                        <td>{{$phoneType->name_en}}</td>
                        <td>
                            <a title="تعديل" href="/webadmin/phone_types/{{$phoneType->id}}/edit"><i
                                    class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/phone_types/{{ $phoneType->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$phoneTypes->links()}}
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/countrcountriess!!}--}}
@endsection