routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {
    return view('landing');
});


Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/login', function () {
        return view('welcome');
    });
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::get('/engineers', 'admin\UsersController@listEngineers');
    Route::resource('/orders', 'admin\OrderController');
    Route::resource('/problems', 'admin\ProblemController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/states', 'admin\StatesController');
    Route::resource('/phone_types', 'admin\PhoneTypesController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/products', 'admin\ProductController');
    Route::get('/phone_models/samsung', 'admin\PhoneModelsController@listSamsung');
    Route::get('/phone_models/huawei', 'admin\PhoneModelsController@listHuawei');
    Route::resource('/phone_models', 'admin\PhoneModelsController');
    Route::get('/phone_colors/samsung', 'admin\PhoneColorsController@listSamsung');
    Route::get('/phone_colors/huawei', 'admin\PhoneColorsController@listHuawei');
    Route::resource('/phone_colors', 'admin\PhoneColorsController');
    Route::resource('/accessory_types', 'admin\AccessoriesTypesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/transactions', 'admin\TransactionsController');
    Route::get('/transactions/{id}/paid', 'admin\TransactionsController@paid');
    Route::get('/transactions/{id}/ban', 'admin\TransactionsController@ban');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');

    Route::get('/notifications', 'admin\UsersController@showNotification');
    Route::post('/send_notification', 'admin\UsersController@sendNotification');


});
Route::get('/getStates', function () {
    $city_id = Input::get('city_id');
    $states = \App\Models\State::where('city_id', '=', $city_id)->get();
    return json_encode($states);
});

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $table = 'states';
    protected $guarded = [];

    public $timestamps = true;

    public function city()
    {
        return $this->belongsTo(City::class, 'city_id');
    }
}

app/Http/Controllers/admin/StatesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Area;
use App\Models\City;
use App\Models\State;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = State::orderBy('city_id', 'asc')->latest()->paginate(10);
        return view('admin.states.index', compact('states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::all();
        return view('admin.states.add', compact('cities'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
            'city_id' => 'required',
        ]);
        State::create($request->all());
        return redirect('/webadmin/states')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم اضافة الحى بنجاح']));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cities = City::all();
        $state = State::find($id);
        return view('admin.states.edit', compact('cities', 'state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
            'city_id' => 'required',
        ]);
        State::find($id)->update($request->all());
        return redirect('/webadmin/states')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم تعديل الحى بنجاح']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        State::destroy($id);
        return redirect('/webadmin/states')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم حذف الحى بنجاح']));
    }
}

resources/views/admin/states/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة حي
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dahboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('webadmin/states')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاحياء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="{{url('/webadmin/states/create')}}" class="m-menu__link">
            <span class="m-menu__link-text">اضافة حي</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة حي
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->

        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/states" method="post">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.states.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/states/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل حي
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/wbadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/states')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاحياء </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل حي</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل حي
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($state,['route' => ['states.update' , $state->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right']) !!}
        <div class="m-portlet__body">
            @include('admin.states.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/states/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">اسم الحي بالعربية</label>
    <div class="col-lg-4{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
        {!! Form::text('name_ar',null,['class'=>'form-control m-input','autofocus','placeholder'=>"اسم الحي بالعربية"]) !!}
        @if ($errors->has('name_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_ar') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-2 col-form-label">اسم الحي بالانلجيزية</label>
    <div class="col-lg-4{{ $errors->has('name_en') ? ' has-danger' : '' }}">
        {!! Form::text('name_en',null,['class'=>'form-control m-input','placeholder'=>"اسم الحي بالانلجيزية"]) !!}
        @if ($errors->has('name_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_en') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
<label class="col-lg-2 col-form-label">المنطقة التابع لها</label>
<div class="col-lg-10{{ $errors->has('city_id') ? ' has-danger' : '' }}">
    <select name="city_id" class="form-control">
        <option value="" disabled selected>اختر المنطقة</option>
        @foreach($cities as $city)
        <option value="{{$city->id}}" {{isset($state) && $state->city_id==$city->id?'selected':'' }} {{old('city_id')==$city->id? 'selected':''}}>{{$city->name_ar}}</option>
            @endforeach

    </select>
    @if ($errors->has('city_id'))
        <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('city_id') }}</strong>
            </span>
    @endif
</div>
</div>

resources/views/admin/states/index.blade.php
@extends('admin.layouts.app')
@section('title')
    الاحياء
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text"> الاحياء</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاحياء
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('states.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger"><i
                        class=" fa fa-edit"></i> اضف حي</a></div>

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_country">
                <thead>
                <tr>
                    {{--<th>#</th>--}}
                    <th>اسم الحي بالعربية</th>
                    <th>اسم الحي بالانجليزية</th>
                    <th>المنطقة التابع لها</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($states as $i => $state)
                    <tr>
                        {{--                        <td>{{$state->id}}</td>--}}
                        <td>{{$state->name_ar}}</td>
                        <td>{{$state->name_en}}</td>
                        <td>{{$state->city ?$state->city->name_ar:''}}</td>
                        <td>
                            <a title="Edit" href="/webadmin/states/{{$state->id}}/edit"><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/states/{{ $state->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
            {{$states->links()}}
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/currencies.js') !!}--}}
@endsection