routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {
    return view('landing');
});


Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/login', function () {
        return view('welcome');
    });
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::get('/engineers', 'admin\UsersController@listEngineers');
    Route::resource('/orders', 'admin\OrderController');
    Route::resource('/problems', 'admin\ProblemController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/states', 'admin\StatesController');
    Route::resource('/phone_types', 'admin\PhoneTypesController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/products', 'admin\ProductController');
    Route::get('/phone_models/samsung', 'admin\PhoneModelsController@listSamsung');
    Route::get('/phone_models/huawei', 'admin\PhoneModelsController@listHuawei');
    Route::resource('/phone_models', 'admin\PhoneModelsController');
    Route::get('/phone_colors/samsung', 'admin\PhoneColorsController@listSamsung');
    Route::get('/phone_colors/huawei', 'admin\PhoneColorsController@listHuawei');
    Route::resource('/phone_colors', 'admin\PhoneColorsController');
    Route::resource('/accessory_types', 'admin\AccessoriesTypesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/transactions', 'admin\TransactionsController');
    Route::get('/transactions/{id}/paid', 'admin\TransactionsController@paid');
    Route::get('/transactions/{id}/ban', 'admin\TransactionsController@ban');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');

    Route::get('/notifications', 'admin\UsersController@showNotification');
    Route::post('/send_notification', 'admin\UsersController@sendNotification');


});
Route::get('/getStates', function () {
    $city_id = Input::get('city_id');
    $states = \App\Models\State::where('city_id', '=', $city_id)->get();
    return json_encode($states);
});

app/User.php
<?php

namespace App;

use App\Models\City;
use App\Models\State;
use App\Models\Transaction;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

//    protected $dates = ['deleted_at'];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function city()
    {
        return $this->belongsTo(City::class, 'city_id');
    }

    public function state()
    {
        return $this->belongsTo(State::class, 'state_id');
    }
    public function transactions()
    {
        return $this->hasMany(State::class, 'user_id');
    }
    public function balance(){
        return Transaction::where('user_id',$this->id)->where('paid',0)->sum('amount');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;
use App\Http\Requests\CompleteProfileRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\Http\Resources\AddressCollection;
use App\Http\Resources\UserProfileResource;
use App\Models\Notification;
use App\Models\FixOrder;
use App\Models\UserAddress;
use App\User;
use Carbon\Carbon;
use Helpers;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;


class UserController extends Controller
{
    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'phone' => [
                'required',
                'regex:/^(05|5)([0-9]{8})$/',
            ],
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()], 400);
        }

        $user = User::firstOrCreate([
            'phone' => request('phone')
        ]);

        if ($user) {
            $code = rand(1111, 9999);
//            $code = 5698;
            $user->update([
                'login_code' => $code,
//                'code_expire_at' => Carbon::now()->addMinutes(5)
                'code_expire_at' => Carbon::now()->addMonths(5)
            ]);

            $messageContent = 'كود التفعيل : ' . $code;
            Helpers::send_sms($messageContent, $user->phone);
        }
        return response()->json([
            'user_id' => $user->id,
            'login_code' => $user->login_code,
        ], 200);
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function verifyUser(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'login_code' => 'required',
            'user_id' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()], 400);
        }

        $login_code = $request->login_code;
        $user_id = $request->user_id;

        $user = User::find($user_id);

        if (!$user) {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        if ($user->login_code == $login_code) {
            if (Carbon::now() > $user->code_expire_at) {
                if (request()->header('Accept-Language') == 'ar')
                    $message = 'الكود منتهي .. برجاء الحصول على كود جديد';
                else
                    $message = 'expired login code, get new one';
                return response()->json(['error' => $message], 400);
            }

            if ($user->tokens == null) {
                $access_token = Helpers::generateRandomString();
                $user->update([
                    'tokens' => $access_token,
                ]);
            }
            $user->type == 1 ? $user_type = 'user' : $user_type = 'engineer';

            Helpers::updateFCMToken($user);

            return response()->json([
                'complete_data' => $user->name != null ? true : false,
                'user_type' => $user_type,
                'user_name' => $user->name ? $user->name : '',
                'user_image' => $user->photo ? \Helpers::base_url() . '/' . $user->photo : '',
                'joined_from' => $user->created_at ? $user->created_at->toDateString() : '',
                'fcm_token' => $user->device_token,
                'access_token' => $user->tokens,
            ], 200);

        } else {
            if (request()->header('Accept-Language') == 'ar')
                $message = 'الكود غير صالح';
            else
                $message = 'Invalid login code';
            return response()->json(['error' => $message], 400);
        }
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function resendUserActivationCode(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'user_id' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()], 400);
        }
        $user = User::find($request->user_id);

        if (!$user) {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }

        $code = rand(1111, 9999);
//        $code = 5698;
        $user->update([
            'login_code' => $code,
        ]);

        $messageContent = 'كود التفعيل : ' . $code;
        Helpers::send_sms($messageContent, $user->phone);

        $user->save();

        return response()->json([], 204);
    }


    /**
     * @param CompleteProfileRequest $request
     * @return JsonResponse
     */
    public function completeProfile(CompleteProfileRequest $request)
    {
        $user = User::find($request->user_id);

        $user->update([
            'name' => $request->name,
            'city_id' => $request->city_id,
            'state_id' => $request->state_id,
        ]);

        Helpers::updateFCMToken($user);
        return response()->json([], 204);
    }

    /**
     * @return JsonResponse
     */
    public function getProfile()
    {
        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }

        return response()->json(new UserProfileResource($user), 200);
    }

    /**
     * @param Request $request
     * @return mixed|void
     */
    public function changeProfilePicture(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'image' => 'mimes:jpeg,jpg,png,gif|required|image',
        ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()], 400);
        }

        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();

        if ($request->hasfile('image')) {
            $file = $request->file('image');
            $filepath = 'images/users/' . date('Y') . '/' . date('m') . '/';
            $filename = $filepath . time() . '-' . $file->getClientOriginalName();
            $file->move($filepath, $filename);
            $user->photo = $filename;
            $user->save();
        }

        return response()->json(['image' => \Helpers::base_url() . '/' . $user->photo], 200);
    }


    /**
     * @return JsonResponse
     */
    public function logout()
    {
        $user = Helpers::getLoggedUser();
        if (!$user) {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $user->update([
            'device_token' => null
        ]);
        return response()->json([], 204);
    }

    /**
     * @return JsonResponse
     */
    public function getUserAddresses()
    {
        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $addresses = UserAddress::where('user_id', $user->id)->get();

        return response()->json(new AddressCollection($addresses), 200);
    }

    /**
     * @param UpdateProfileRequest $request
     * @return JsonResponse
     */
    public function updateProfile(UpdateProfileRequest $request)
    {
        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $user->update([
            'name' => $request->name,
            'city_id' => $request->city_id,
            'state_id' => $request->state_id,
            'phone' => $request->phone
        ]);
        return response()->json([], 204);
    }


    /**
     * @param Request $request
     * @return mixed|string
     *
     */
    public function updateOldPassword(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'old_password' => 'required',
            'new_password' => 'required|min:6',
            'confirm_password' => 'required|same:new_password'
        ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()], 400);
        }


        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        if (Hash::check($request->old_password, $user->password)) {

            if (Hash::check($request->new_password, $user->password)) {
                return response()->json(['error' => 'same_old_password'], 400);
            } else {
                $user->update([
                    'password' => bcrypt($request->new_password)
                ]);
                return response()->json([], 204);
            }
        } else {
            return response()->json(['error' => 'wrong password'], 400);
        }
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function addAddress(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'city_id' => 'required',
            'state_id' => 'required',
            'full_address' => 'required',
            'latitude' => 'required',
            'longitude' => 'required'
        ],
            [
                'city_id.required' => trans('messages.add_address_city_id_required'),
                'state_id.required' => 'state_id required',

resources/views/admin/users/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة عضو
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة عضو</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        اضافة عضو
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/users" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.users.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل العضو
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تعديل عضو</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل عضو
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($user,['route' => ['users.update' , $user->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.users.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/users/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">الاسم</label>
    <div class="col-lg-5{{ $errors->has('name') ? ' has-danger' : '' }}">
        {!! Form::text('name',old('name'),['class'=>'form-control m-input','autofocus','placeholder'=> 'الاسم' ]) !!}
        @if ($errors->has('name'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>

    <label class="col-lg-1 col-form-label">الهاتف</label>
    <div class="col-lg-5{{ $errors->has('phone') ? ' has-danger' : '' }}">
        {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','placeholder'=> 'الهاتف' ]) !!}
        @if ($errors->has('phone'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
    </div>
</div>


{{--<div class="form-group m-form__group row">--}}
{{--    <label class="col-lg-1 col-form-label">البريد الالكتروني</label>--}}
{{--    <div class="col-lg-5{{ $errors->has('email') ? ' has-danger' : '' }}">--}}
{{--        {!! Form::text('email',old('email'),['class'=>'form-control m-input','placeholder'=> 'البريد الالكتروني' ]) !!}--}}
{{--        @if ($errors->has('email'))--}}
{{--            <span class="form-control-feedback" role="alert">--}}
{{--                <strong>{{ $errors->first('email') }}</strong>--}}
{{--            </span>--}}
{{--        @endif--}}
{{--    </div>--}}
{{--    <label class="col-lg-1 col-form-label">كلمة المرور </label>--}}
{{--    <div class="col-lg-5{{ $errors->has('password') ? ' has-danger' : '' }}">--}}
{{--        {!! Form::password('password',['class'=>'form-control m-input','placeholder'=> 'كلمة المرور' ]) !!}--}}
{{--        @if ($errors->has('password'))--}}
{{--            <span class="form-control-feedback" role="alert">--}}
{{--                <strong>{{ $errors->first('password') }}</strong>--}}
{{--            </span>--}}
{{--        @endif--}}
{{--    </div>--}}

{{--</div>--}}
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">المنطقة</label>
    <div class="col-lg-5{{ $errors->has('city_id') ? ' has-danger' : '' }}">
        {{--{!! Form::text('phone',old('phone'),['class'=>'form-control m-input','placeholder'=> 'Phone' ]) !!}--}}
        <select name="city_id" id="city_id" class="form-control m-input" >
            <option value="">--اختر المنطقة --</option>
            @foreach($cities as $city)
                <option value="{{$city->id}}" {{isset($user) && $user->city_id==$city->id ?'selected':''}}>{{$city->name_ar}}</option>
                @endforeach

        </select>
        @if ($errors->has('city_id'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('city_id') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">الحي</label>
    <div class="col-lg-5{{ $errors->has('state_id') ? ' has-danger' : '' }}">
        <select name="state_id" id="state_id" class="form-control m-input" >
            <option value="">--اختر الحي --</option>
            @isset($user)
                @foreach($user->city->states as $state)
                    <option value="{{$state->id}}" {{isset($user) && $user->state_id==$state->id ?'selected':''}}>{{$state->name_ar}}</option>

                @endforeach
            @endisset


        </select>
        @if ($errors->has('state_id'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('state_id') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">نوع العضو</label>
    <div class="col-lg-11{{ $errors->has('type') ? ' has-danger' : '' }}">
        <select name="type"  class="form-control m-input" >
            <option value="">--اختر نوع العضو--</option>
                <option value="2" {{isset($user) && $user->type==2 ?'selected':''}}>مهندس</option>
                <option value="1" {{isset($user) && $user->type==1 ?'selected':''}} >عضو عادي</option>


        </select>
        @if ($errors->has('type'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('type') }}</strong>
            </span>
        @endif
    </div>

</div>

<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">الصورة الشخصية</label>
    <div class="col-lg-11{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($user) && $user->photo)
<div class="row">




            <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                <img
                        data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                        alt="First slide [800x4a00]"
                        src="{{asset($user->photo)}}"
                        style="height: 150px; width: 150px"
                        data-holder-rendered="true">
            </div>

</div>
@endif

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('title')
    الاعضاء
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/users')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاعضاء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاعضاء
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('users.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i>اضف عضو</a></div>
            <br>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>الهاتف</th>
                    <th>البريد الالكتروني</th>
                    <th>المنطقة</th>
                    <th>النوع</th>
                    <th>الرصيد</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $index=> $user)
                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$user->name}} </td>
                        <td>{{$user->phone}} </td>
                        <td>{{$user->email}} </td>
                        <td>{{$user->city ? $user->city->name_ar : '---------'}} </td>
                        <td>{{$user->type == 1 ? 'user' : 'engineer'}} </td>
                        <td>{{$user->balance() == 0 ?0:- $user->balance() }} </td>

                        <td>


                            <a title="Show Details" href="/webadmin/users/{{$user->id}}"><i class="fa fa-eye"></i></a>
                            {{--<a  title="Bank Data" href="/webadmin/user/{{$user->id}}/bank-data" ><i class="fa fa-credit-card"></i></a>--}}
                            <a title="Edit" href="/webadmin/users/{{$user->id}}/edit"><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/users/{{ $user->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection