routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {
    return view('landing');
});


Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/login', function () {
        return view('welcome');
    });
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::get('/engineers', 'admin\UsersController@listEngineers');
    Route::resource('/orders', 'admin\OrderController');
    Route::resource('/problems', 'admin\ProblemController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/states', 'admin\StatesController');
    Route::resource('/phone_types', 'admin\PhoneTypesController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/products', 'admin\ProductController');
    Route::get('/phone_models/samsung', 'admin\PhoneModelsController@listSamsung');
    Route::get('/phone_models/huawei', 'admin\PhoneModelsController@listHuawei');
    Route::resource('/phone_models', 'admin\PhoneModelsController');
    Route::get('/phone_colors/samsung', 'admin\PhoneColorsController@listSamsung');
    Route::get('/phone_colors/huawei', 'admin\PhoneColorsController@listHuawei');
    Route::resource('/phone_colors', 'admin\PhoneColorsController');
    Route::resource('/accessory_types', 'admin\AccessoriesTypesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/transactions', 'admin\TransactionsController');
    Route::get('/transactions/{id}/paid', 'admin\TransactionsController@paid');
    Route::get('/transactions/{id}/ban', 'admin\TransactionsController@ban');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');

    Route::get('/notifications', 'admin\UsersController@showNotification');
    Route::post('/send_notification', 'admin\UsersController@sendNotification');


});
Route::get('/getStates', function () {
    $city_id = Input::get('city_id');
    $states = \App\Models\State::where('city_id', '=', $city_id)->get();
    return json_encode($states);
});

app/Models/PhoneColor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PhoneColor extends Model
{
    protected $table = 'phone_colors';
    protected $guarded = [];

    public $timestamps = true;

    public function phoneModel()
    {
        return $this->belongsTo(PhoneModel::class, 'phone_model_id');
    }

}

app/Http/Controllers/admin/PhoneColorsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\PhoneColor;
use App\Models\PhoneModel;
use App\Models\PhoneTypes;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PhoneColorsController extends Controller
{
    public function index()
    {
        $phoneTypes = PhoneTypes::find(1);
        $phoneColors = PhoneColor::whereHas('phoneModel', function ($q) use ($phoneTypes) {
            $q->where('phone_type_id', $phoneTypes->id);
        })->paginate(10);
        return view('admin.phoneColors.index', compact('phoneColors'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\View\View
     */
    public function listHuawei()
    {
        $phoneTypes = PhoneTypes::where('name_en', 'huawei')->first();
        $phoneColors = PhoneColor::whereHas('phoneModel', function ($q) use ($phoneTypes) {
            $q->where('phone_type_id', $phoneTypes->id);
        })->paginate(10);
        return view('admin.phoneColors.index', compact('phoneColors'));
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\View\View
     */
    public function listSamsung()
    {
        $phoneTypes = PhoneTypes::where('name_en', 'samsung')->first();
        if ($phoneTypes) {
            $phoneColors = PhoneColor::whereHas('phoneModel', function ($q) use ($phoneTypes) {
                $q->where('phone_type_id', $phoneTypes->id);
            })->paginate(10);
        }
        return view('admin.phoneColors.index', compact('phoneColors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $phoneModels = PhoneModel::all();
        return view('admin.phoneColors.add', compact('phoneModels'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
            'phone_model_id' => 'required',
        ]);
        PhoneColor::create($request->all());
        $phoneModel = PhoneModel::find($request->phone_model_id);
        if ($phoneModel->phone_type_id == 1)
            $redirect = 'phone_colors';
        elseif ($phoneModel->phone_type_id == 2)
            $redirect = 'phone_colors/huawei';
        else
            $redirect = 'phone_colors/samsung';

        return redirect('/webadmin/' . $redirect)->withFlashMessage(json_encode(['success' => true, 'msg' => 'تمت الاضافة بنجاح']));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $phoneModels = phoneModel::all();
        $phoneColor = PhoneColor::find($id);
        return view('admin.phoneColors.edit', compact('phoneModels', 'phoneColor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name_ar' => 'required',
            'name_en' => 'required',
            'phone_model_id' => 'required',
        ]);
        PhoneColor::find($id)->update($request->all());
        $phoneModel = PhoneModel::find($request->phone_model_id);
        if ($phoneModel->phone_type_id == 1)
            $redirect = 'phone_colors';
        elseif ($phoneModel->phone_type_id == 2)
            $redirect = 'phone_colors/huawei';
        else
            $redirect = 'phone_colors/samsung';

        return redirect('/webadmin/' . $redirect)->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم تعديل لون الهاتف بنجاح']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PhoneColor::destroy($id);
        return redirect('/webadmin/phone_colors')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم حذف نوع الهاتف بنجاح']));
    }
}

resources/views/admin/phoneColors/add.blade.php
@extends('admin.layouts.app')

@section('title')
    اضافة لون هاتف
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dahboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('webadmin/phone_colors')}}" class="m-menu__link">
            <span class="m-menu__link-text">ألوان الهواتف</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="{{url('/webadmin/phone_colors/create')}}" class="m-menu__link">
            <span class="m-menu__link-text">اضافة لون هاتف</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة لون هاتف
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->

        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/phone_colors" method="post">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.phoneColors.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/phoneColors/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل لون هاتف
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/wbadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/phone_colors')}}" class="m-menu__link">
            <span class="m-menu__link-text">ألوان الهواتف</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل لون هاتف </span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل لون هاتف
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($phoneColor,['route' => ['phone_colors.update' , $phoneColor->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right']) !!}
        <div class="m-portlet__body">
            @include('admin.phoneColors.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/phoneColors/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">لون الهاتف بالعربية: </label>
    <div class="col-lg-4{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
        {!! Form::text('name_ar',null,['class'=>'form-control m-input','autofocus','placeholder'=>"لون الهاتف بالعربية"]) !!}
        @if ($errors->has('name_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_ar') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-2 col-form-label">لون الهاتف بالانجليزية : </label>
    <div class="col-lg-4{{ $errors->has('name_en') ? ' has-danger' : '' }}">
        {!! Form::text('name_en',null,['class'=>'form-control m-input','placeholder'=>"لون الهاتف بالانجليزية"]) !!}
        @if ($errors->has('name_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_en') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
<label class="col-lg-2 col-form-label">موديل الهاتف : </label>
<div class="col-lg-10{{ $errors->has('phone_model_id') ? ' has-danger' : '' }}">
    <select name="phone_model_id" class="form-control">
        <option value="" disabled selected>اختر موديل الهاتف</option>
        @foreach($phoneModels as $phoneModel)
        <option value="{{$phoneModel->id}}" {{isset($phoneColor) && $phoneColor->phone_model_id==$phoneModel->id?'selected':'' }} {{old('phone_model_id')==$phoneModel->id? 'selected':''}}>{{$phoneModel->name_ar}}</option>
            @endforeach

    </select>
    @if ($errors->has('phone_model_id'))
        <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('phone_model_id') }}</strong>
            </span>
    @endif
</div>
</div>

resources/views/admin/phoneColors/index.blade.php
@extends('admin.layouts.app')
@section('title')
    ألوان الهواتف
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text"> ألوان الهواتف</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        ألوان الهواتف
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('phone_colors.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضافة لون هاتف</a></div>

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_testArea">
                <thead>
                <tr>
                    {{--<th>#</th>--}}
                    <th>لون الهاتف بالعربية</th>
                    <th>لون الهاتف بالانجليزية</th>
                    <th>موديل الهاتف</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($phoneColors))
                    @foreach($phoneColors as $i => $phoneColor)
                        <tr>
                            {{--                        <td>{{$index + $phoneColors->firstItem()}}</td>--}}
                            <td>{{$phoneColor->name_ar}}</td>
                            <td>{{$phoneColor->name_en}}</td>
                            <td>{{$phoneColor->phoneModel ?$phoneColor->phoneModel->name_ar:''}}</td>
                            <td>
                                <a title="تعديل" href="/webadmin/phone_colors/{{$phoneColor->id}}/edit"><i
                                        class="fa fa-edit"></i></a>
                                <form class="inline-form-style"
                                      action="/webadmin/phone_colors/{{ $phoneColor->id }}"
                                      method="post">
                                    <button type="submit" class="trash-btn">
                                        <span class="fa fa-trash"></span>
                                    </button>
                                    <input type="hidden" name="_method" value="delete"/>
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                </form>
                            </td>
                        </tr>

                    @endforeach
                @endif
                </tbody>
            </table>
            {{$phoneColors->links()}}
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/currencies.js') !!}--}}
@endsection